name: Java Heap Dump

on:
  workflow_dispatch:
    inputs:
      namespace:
        description: "Kubernetes Namespace"
        required: true
        default: "demo"

      pod:
        description: "Pod Name"
        required: true
        default: "java-test-pod"

jobs:
  heap-dump:

    runs-on:
      - self-hosted

    steps:

      - uses: actions/checkout@v4

      - name: Verify Cluster
        run: |
          kubectl cluster-info
          kubectl get nodes

      - name: Verify Pod
        run: |
          kubectl get pod \
          ${{ github.event.inputs.pod }} \
          -n ${{ github.event.inputs.namespace }}

      - name: Verify Java
        run: |
          kubectl exec \
          -n ${{ github.event.inputs.namespace }} \
          ${{ github.event.inputs.pod }} \
          -- java -version

      - name: Find Java PID
        shell: bash
        run: |
          PID=$(kubectl exec \
            -n ${{ github.event.inputs.namespace }} \
            ${{ github.event.inputs.pod }} \
            -- jcmd | awk '$2 !~ /JCmd/ {print $1; exit}')

          echo "PID=$PID"
          echo "PID=$PID" >> $GITHUB_ENV

      - name: Generate Heap Dump
        run: |

          kubectl exec \
            -n ${{ github.event.inputs.namespace }} \
            ${{ github.event.inputs.pod }} \
            -- jcmd $PID GC.heap_dump /tmp/heap.hprof

      - name: Copy Heap Dump
        run: |

          kubectl cp \
          ${{ github.event.inputs.namespace }}/${{ github.event.inputs.pod }}:/tmp/heap.hprof \
          heap.hprof

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Heap-Dump
          path: heap.hprof
